# Generated by Django 3.1.1 on 2020-09-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDatas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDLST_NM', models.CharField(max_length=50)),
                ('PRDLST_DCNM', models.CharField(max_length=50)),
                ('BSSH_NM', models.CharField(max_length=50)),
                ('PRMS_DT', models.CharField(max_length=50)),
                ('RAWMTRL_NM', models.TextField()),
                ('LCNS_NO', models.CharField(max_length=50)),
                ('PRDLST_REPORT_NO', models.CharField(max_length=50)),
            ],
        ),
    ]
