# Generated by Django 3.1.1 on 2020-09-22 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200918_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooddatas',
            name='GOOD',
        ),
        migrations.RemoveField(
            model_name='fooddatas',
            name='NOT_GOOD',
        ),
    ]
