# Generated by Django 3.1.1 on 2020-10-09 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200922_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitoStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RW_NAME', models.CharField(max_length=50)),
                ('RW_LEVEL', models.IntegerField(choices=[(1, 'Verygood'), (2, 'Good'), (3, 'Bad'), (4, 'Fuckingbad')])),
                ('RW_EXPLAIN', models.TextField()),
            ],
        ),
    ]
