# Generated by Django 3.1.1 on 2020-11-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_kitostandard'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddatas',
            name='PRDLST_NM_NOSAPACE',
            field=models.CharField(default='PleaseUpLoad', max_length=200),
        ),
    ]
