# Generated by Django 3.1.1 on 2020-11-04 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_fooddatas_prdlst_nm_nosapace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooddatas',
            old_name='PRDLST_NM_NOSAPACE',
            new_name='PRDLST_NM_NOSPACE',
        ),
    ]
