# Generated by Django 3.1.1 on 2020-11-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201104_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutData',
            fields=[
                ('NUTR_CONT3', models.CharField(max_length=50)),
                ('NUTR_CONT2', models.CharField(max_length=50)),
                ('NUTR_CONT1', models.CharField(max_length=50)),
                ('SERVING_SIZE', models.CharField(max_length=50)),
                ('MAKER_NAME', models.CharField(max_length=50)),
                ('NUTR_CONT9', models.CharField(max_length=50)),
                ('NUTR_CONT8', models.CharField(max_length=50)),
                ('FOOD_CD', models.CharField(max_length=50)),
                ('NUTR_CONT7', models.CharField(max_length=50)),
                ('NUTR_CONT6', models.CharField(max_length=50)),
                ('NUTR_CONT5', models.CharField(max_length=50)),
                ('NUTR_CONT4', models.CharField(max_length=50)),
                ('DESC_KOR', models.CharField(max_length=50)),
                ('SAMPLING_MONTH_NAME', models.CharField(max_length=50)),
                ('SUB_REF_NAME', models.CharField(max_length=50)),
                ('SAMPLING_REGION_NAME', models.CharField(max_length=50)),
                ('GROUP_NAME', models.CharField(max_length=50)),
                ('RESEARCH_YEAR', models.CharField(max_length=50)),
                ('SAMPLING_REGION_CD', models.CharField(max_length=50)),
                ('SAMPLING_MONTH_CD', models.CharField(max_length=50)),
                ('NUM', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='fooddatas',
            name='SEARCH_SCORE',
            field=models.IntegerField(default=0),
        ),
    ]
