# Generated by Django 3.1.1 on 2020-11-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201108_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutdata',
            name='SEARCH_SCORE',
            field=models.IntegerField(default=0),
        ),
    ]
