# Generated by Django 3.1.1 on 2020-11-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_nutdata_search_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutdata',
            name='DESC_KOR',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='nutdata',
            name='GROUP_NAME',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='nutdata',
            name='MAKER_NAME',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='nutdata',
            name='SAMPLING_MONTH_NAME',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='nutdata',
            name='SAMPLING_REGION_NAME',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='nutdata',
            name='SUB_REF_NAME',
            field=models.CharField(max_length=200),
        ),
    ]
